import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { PrismaClient, Role, AttendanceStatus } from '@prisma/client';
import { z } from 'zod';

const prisma = new PrismaClient();
const app = express();
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') ?? true }));
app.use(express.json());
const JWT_SECRET = process.env.JWT_SECRET || 'dev_secret_change_me';
type AuthRequest = express.Request & { user?: { id: number; role: Role } };
function sign(user: { id:number; role:Role }) { return jwt.sign(user, JWT_SECRET, { expiresIn:'8h' }); }
function auth(req:AuthRequest,res:express.Response,next:express.NextFunction){ const token=req.headers.authorization?.replace('Bearer ',''); if(!token)return res.status(401).json({message:'Authentication required'}); try{req.user=jwt.verify(token,JWT_SECRET) as any;next()}catch{return res.status(401).json({message:'Invalid or expired token'})}}
function role(...roles:Role[]){return (req:AuthRequest,res:express.Response,next:express.NextFunction)=>{if(!req.user||!roles.includes(req.user.role))return res.status(403).json({message:'Forbidden'});next()}}
app.get('/health',async(_req,res)=>{try{await prisma.$queryRaw\`SELECT 1\`;res.json({status:'healthy',database:'connected'})}catch{res.status(503).json({status:'unhealthy',database:'disconnected'})}});
app.get('/metrics',async(_req,res)=>{res.type('text/plain').send('# HELP attendance_api_up API health\n# TYPE attendance_api_up gauge\nattendance_api_up 1\n')});
app.post('/api/auth/login',async(req,res)=>{const p=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid login payload'});const u=await prisma.user.findUnique({where:{email:p.data.email}});if(!u||!u.active||!(await bcrypt.compare(p.data.password,u.passwordHash)))return res.status(401).json({message:'Invalid credentials'});res.json({token:sign({id:u.id,role:u.role}),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/auth/me',auth,async(req:AuthRequest,res)=>res.json(await prisma.user.findUnique({where:{id:req.user!.id},select:{id:true,name:true,email:true,role:true}})));
app.get('/api/student/dashboard',auth,role(Role.STUDENT),async(req:AuthRequest,res)=>{const s=await prisma.student.findUnique({where:{userId:req.user!.id}});if(!s)return res.status(404).json({message:'Student profile not found'});const rows=await prisma.attendance.findMany({where:{studentId:s.id},include:{subject:true},orderBy:{date:'asc'}});const total=rows.length,present=rows.filter(r=>r.status==='PRESENT'||r.status==='LATE').length;const bySubject=Object.values(rows.reduce((a:any,r)=>{a[r.subject.code]??={subject:r.subject.name,total:0,present:0};a[r.subject.code].total++;if(r.status==='PRESENT'||r.status==='LATE')a[r.subject.code].present++;return a},{}));const trend=rows.reduce((a:any[],r)=>{const key=r.date.toISOString().slice(0,10);let x=a.find(v=>v.date===key);if(!x){x={date:key,present:0,total:0};a.push(x)}x.total++;if(r.status==='PRESENT'||r.status==='LATE')x.present++;return a},[]);res.json({overall:total?Math.round(present/total*1000)/10:0,total,present,absent:total-present,bySubject,trend})});
app.get('/api/student/attendance',auth,role(Role.STUDENT),async(req:AuthRequest,res)=>{const s=await prisma.student.findUnique({where:{userId:req.user!.id}});if(!s)return res.status(404).json({message:'Student profile not found'});res.json(await prisma.attendance.findMany({where:{studentId:s.id},include:{subject:true},orderBy:{date:'desc'}}))});
app.get('/api/teacher/classes',auth,role(Role.TEACHER),async(req:AuthRequest,res)=>{const t=await prisma.teacher.findUnique({where:{userId:req.user!.id}});if(!t)return res.status(404).json({message:'Teacher profile not found'});res.json(await prisma.subject.findMany({where:{teacherId:t.id},include:{class:true}}))});
app.get('/api/teacher/students',auth,role(Role.TEACHER),async(req:AuthRequest,res)=>{const t=await prisma.teacher.findUnique({where:{userId:req.user!.id}});const subjectId=Number(req.query.subjectId);if(!t||!subjectId)return res.status(400).json({message:'subjectId required'});const sub=await prisma.subject.findFirst({where:{id:subjectId,teacherId:t.id}});if(!sub)return res.status(403).json({message:'Subject not assigned'});const es=await prisma.enrollment.findMany({where:{classId:sub.classId},include:{student:{include:{user:true}}}});res.json(es.map(e=>({id:e.student.id,rollNo:e.student.rollNo,name:e.student.user.name})))});
app.post('/api/teacher/attendance',auth,role(Role.TEACHER),async(req:AuthRequest,res)=>{const p=z.object({subjectId:z.number().int(),date:z.string(),records:z.array(z.object({studentId:z.number().int(),status:z.nativeEnum(AttendanceStatus)}))}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid attendance payload'});const t=await prisma.teacher.findUnique({where:{userId:req.user!.id}});if(!t)return res.status(404).json({message:'Teacher profile not found'});const sub=await prisma.subject.findFirst({where:{id:p.data.subjectId,teacherId:t.id}});if(!sub)return res.status(403).json({message:'Subject not assigned'});const date=new Date(p.data.date);for(const r of p.data.records)await prisma.attendance.upsert({where:{studentId_subjectId_date:{studentId:r.studentId,subjectId:sub.id,date}},update:{status:r.status,classId:sub.classId,teacherId:t.id},create:{studentId:r.studentId,subjectId:sub.id,classId:sub.classId,teacherId:t.id,date,status:r.status}});await prisma.auditLog.create({data:{userId:req.user!.id,action:'MARK_ATTENDANCE',entity:'ATTENDANCE',details:`subject=${sub.code}, date=${p.data.date}`}});res.json({message:'Attendance saved'})});
app.get('/api/admin/stats',auth,role(Role.ADMIN),async(_req,res)=>{const [students,teachers,classes,subjects]=await Promise.all([prisma.student.count(),prisma.teacher.count(),prisma.class.count(),prisma.subject.count()]);res.json({students,teachers,classes,subjects})});
app.get('/api/admin/students',auth,role(Role.ADMIN),async(_req,res)=>res.json(await prisma.student.findMany({include:{user:{select:{id:true,name:true,email:true,active:true}}},orderBy:{rollNo:'asc'}})));
app.post('/api/admin/students',auth,role(Role.ADMIN),async(req,res)=>{const p=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),rollNo:z.string().min(1),department:z.string().min(1),semester:z.number().int().min(1).max(12)}).safeParse(req.body);if(!p.success)return res.status(400).json({message:'Invalid student data'});try{const u=await prisma.user.create({data:{name:p.data.name,email:p.data.email,passwordHash:await bcrypt.hash(p.data.password,10),role:Role.STUDENT}});res.status(201).json(await prisma.student.create({data:{userId:u.id,rollNo:p.data.rollNo,department:p.data.department,semester:p.data.semester}}))}catch{res.status(409).json({message:'Email or roll number already exists'})}});
app.get('/api/admin/teachers',auth,role(Role.ADMIN),async(_req,res)=>res.json(await prisma.teacher.findMany({include:{user:{select:{id:true,name:true,email:true,active:true}}},orderBy:{employeeNo:'asc'}})));
app.get('/api/admin/classes',auth,role(Role.ADMIN),async(_req,res)=>res.json(await prisma.class.findMany({include:{_count:{select:{enrollments:true,subjects:true}}}})));
app.get('/api/admin/subjects',auth,role(Role.ADMIN),async(_req,res)=>res.json(await prisma.subject.findMany({include:{class:true,teacher:{include:{user:true}}}})));
app.delete('/api/admin/students/:id',auth,role(Role.ADMIN),async(req,res)=>{const s=await prisma.student.findUnique({where:{id:Number(req.params.id)}});if(!s)return res.status(404).json({message:'Not found'});await prisma.user.delete({where:{id:s.userId}});res.status(204).send()});
const port=Number(process.env.PORT||4000);app.listen(port,()=>console.log(`API listening on ${port}`));
