import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,BarChart,Bar} from 'recharts';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'/api';
const api=axios.create({baseURL:API});
api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
type User={id:number;name:string;email:string;role:'ADMIN'|'TEACHER'|'STUDENT'};
function Login({onLogin}:{onLogin:(u:User)=>void}){const[email,setEmail]=useState('student@demo.local'),[password,setPassword]=useState('Student@123'),[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setError('');try{const r=await api.post('/auth/login',{email,password});localStorage.setItem('token',r.data.token);onLogin(r.data.user)}catch(err){if(axios.isAxiosError(err)){const status=err.response?.status;const message=err.response?.data?.message;if(status)return setError(`${status}: ${message||'Login failed'}`)}setError('Cannot reach the backend API')}}return <div className="login"><form onSubmit={submit} className="card login-card"><h1>Smart Attendance</h1><p className="muted">DevOps-enabled attendance management</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button>Sign in</button><small>Demo: student@demo.local / Student@123</small></form></div>}
function Metric({title,value}:{title:string,value:any}){return <div className="card metric"><span>{title}</span><strong>{value}</strong></div>}
function StudentDashboard(){const[data,setData]=useState<any>(),[rows,setRows]=useState<any[]>([]);useEffect(()=>{Promise.all([api.get('/student/dashboard'),api.get('/student/attendance')]).then(([a,b])=>{setData(a.data);setRows(b.data)})},[]);if(!data)return <div className="loading">Loading...</div>;return <main><div className="grid cards"><Metric title="Overall" value={`${data.overall}%`}/><Metric title="Present" value={data.present}/><Metric title="Absent" value={data.absent}/><Metric title="Total Classes" value={data.total}/></div><section className="card"><h2>Attendance Trend</h2><div className="chart"><ResponsiveContainer width="100%" height={280}><LineChart data={data.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="present" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section><section className="card"><h2>Subject Analytics</h2><div className="chart"><ResponsiveContainer width="100%" height={300}><BarChart data={data.bySubject}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="subject"/><YAxis/><Tooltip/><Bar dataKey="present" name="Present"/></BarChart></ResponsiveContainer></div></section><section className="card"><h2>Attendance History</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Subject</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.date).toLocaleDateString()}</td><td>{r.subject.name}</td><td><span className={`badge ${r.status.toLowerCase()}`}>{r.status}</span></td></tr>)}</tbody></table></div></section></main>}
function TeacherDashboard(){const[subjects,setSubjects]=useState<any[]>([]),[subjectId,setSubjectId]=useState(''),[students,setStudents]=useState<any[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[status,setStatus]=useState<Record<number,string>>({});useEffect(()=>{api.get('/teacher/classes').then(r=>{setSubjects(r.data);if(r.data[0])setSubjectId(String(r.data[0].id))})},[]);useEffect(()=>{if(subjectId)api.get(`/teacher/students?subjectId=${subjectId}`).then(r=>{setStudents(r.data);setStatus(Object.fromEntries(r.data.map((s:any)=>[s.id,'PRESENT'])))})},[subjectId]);async function save(){await api.post('/teacher/attendance',{subjectId:Number(subjectId),date,records:students.map(s=>({studentId:s.id,status:status[s.id]}))});alert('Attendance saved')}return <main><section className="card"><h2>Mark Daily Attendance</h2><div className="form-row"><label>Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="table-wrap"><table><thead><tr><th>Roll No</th><th>Student</th><th>Status</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.rollNo}</td><td>{s.name}</td><td><select value={status[s.id]||'PRESENT'} onChange={e=>setStatus({...status,[s.id]:e.target.value})}><option>PRESENT</option><option>ABSENT</option><option>LATE</option><option>EXCUSED</option></select></td></tr>)}</tbody></table></div><button onClick={save}>Save Attendance</button></section></main>}
function AdminDashboard(){const[stats,setStats]=useState<any>(),[students,setStudents]=useState<any[]>([]);useEffect(()=>{api.get('/admin/stats').then(r=>setStats(r.data));api.get('/admin/students').then(r=>setStudents(r.data))},[]);return <main><div className="grid cards">{stats&&Object.entries(stats).map(([k,v])=><Metric key={k} title={k} value={v}/>)}</div><section className="card"><h2>Students</h2><div className="table-wrap"><table><thead><tr><th>Roll No</th><th>Name</th><th>Email</th><th>Department</th><th>Semester</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.rollNo}</td><td>{s.user.name}</td><td>{s.user.email}</td><td>{s.department}</td><td>{s.semester}</td></tr>)}</tbody></table></div></section></main>}
function App(){const[user,setUser]=useState<User|null>(null);useEffect(()=>{if(localStorage.getItem('token'))api.get('/auth/me').then(r=>setUser(r.data)).catch(()=>localStorage.removeItem('token'))},[]);if(!user)return <Login onLogin={setUser}/>;return <div><header><div><b>Smart Attendance</b><span className="muted"> / {user.role}</span></div><button className="secondary" onClick={()=>{localStorage.removeItem('token');setUser(null)}}>Logout</button></header>{user.role==='STUDENT'?<StudentDashboard/>:user.role==='TEACHER'?<TeacherDashboard/>:<AdminDashboard/>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
